name: mnist
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.8
  - pip
  - pip:
      - tensorboard==2.4.1
      - tensorflow==2.4.1
      - mlflow
      - dvc[webdav]
      - git+https://github.com/MArpogaus/tensorflow-experiments.git@dev
      - git+https://github.com/MArpogaus/TensorFlow-Probability-Bernstein-Polynomial-Bijector.git@1358eb6
      - .
