name: mnist
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.8
  - mlflow
  - dvc
  - holidays==0.13
  - pip
  - pip:
      - wwo-hist==0.0.7
      - git+https://github.com/MArpogaus/tensorflow-experiments.git@6e8b74dc2e912321ebc43ccdd11cc31accc870d3
      - .
