name: mnist
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.8
  - mlflow==1.24.0
  - dvc-webdav==2.9.4
  - holidays==0.13
  - pip
  - pip:
      - wwo-hist==0.0.7
      - git+https://github.com/MArpogaus/tensorflow-experiments.git@86f2099
      - -e .
