- {filters: 20, kernel_size: 2, padding: "causal", activation: "relu", dilation_rate: 1} # 2
- {filters: 20, kernel_size: 2, padding: "causal", activation: "relu", dilation_rate: 2} # 4
- {filters: 20, kernel_size: 2, padding: "causal", activation: "relu", dilation_rate: 4} # 8
- {filters: 20, kernel_size: 2, padding: "causal", activation: "relu", dilation_rate: 8} # 16
- {filters: 20, kernel_size: 2, padding: "causal", activation: "relu", dilation_rate: 16} # 32
- {filters: 20, kernel_size: 2, padding: "causal", activation: "relu", dilation_rate: 32} # 64
- {filters: 20, kernel_size: 2, padding: "causal", activation: "relu", dilation_rate: 64} # 128
- {filters: 20, kernel_size: 2, padding: "causal", activation: "relu", dilation_rate: 128} # 256
- {filters: 10, kernel_size: 1, activation: "linear"}
