seed: 2
model: feed_forward
distribution: bernstein_flow
lr: 0.0001
epochs: 300
output_shape: [20]
distribution_kwds:
  bb_class: !!python/name:bernstein_flow.bijectors.bernstein_extra.BernsteinBijectorLinearExtrapolate
  allow_values_outside_support: true
  clip_to_bernstein_domain: false
  scale_base_distribution: false
