feed_forward:
  batch_normalization: false
  hidden_layers:
  - activation: elu
    kernel_initializer: he_normal
    units: 512
  - activation: elu
    kernel_initializer: he_normal
    units: 256
  - activation: elu
    kernel_initializer: he_normal
    units: 128
wavenet:
  batch_normalization: false
  conv_layers:
  - activation: relu
    dilation_rate: 1
    filters: 20
    kernel_size: 2
    padding: causal
  - activation: relu
    dilation_rate: 2
    filters: 20
    kernel_size: 2
    padding: causal
  - activation: relu
    dilation_rate: 4
    filters: 20
    kernel_size: 2
    padding: causal
  - activation: relu
    dilation_rate: 8
    filters: 20
    kernel_size: 2
    padding: causal
  - activation: relu
    dilation_rate: 16
    filters: 20
    kernel_size: 2
    padding: causal
  - activation: relu
    dilation_rate: 32
    filters: 20
    kernel_size: 2
    padding: causal
  - activation: relu
    dilation_rate: 64
    filters: 20
    kernel_size: 2
    padding: causal
  - activation: relu
    dilation_rate: 128
    filters: 20
    kernel_size: 2
    padding: causal
  - activation: linear
    filters: 10
    kernel_size: 1
  hidden_layers:
  - activation: elu
    kernel_initializer: he_normal
    units: 1024
